In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('patient_data.csv')
dataset.head(10)

,C,Age,History,Patient,TakeMedication,Severity,BreathShortness,VisualChanges,NoseBleeding,Whendiagnoused,Systolic,Diastolic,ControlledDiet,Stages
0,Male,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
1,Female,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
2,Male,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
3,Female,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
4,Male,51-64,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
5,Female,51-64,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
6,Male,65+,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
7,Female,65+,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
8,Male,18-34,Yes,No,No,Sever,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
9,Male,35-50,Yes,Yes,Yes,Sever,Yes,Yes,No,<1 Year,121- 130,91 - 100,Yes,HYPERTENSION (Stage-2)

In [3]:
dataset.isnull().sum()

C                  0
Age                0
History            0
Patient            0
TakeMedication     0
Severity           0
BreathShortness    0
VisualChanges      0
NoseBleeding       0
Whendiagnoused     0
Systolic           0
Diastolic          0
ControlledDiet     0
Stages             0
dtype: int64

In [4]:
dataset.rename(columns={'C':"Gender"}, inplace=True)

In [5]:
dataset.head()

,Gender,Age,History,Patient,TakeMedication,Severity,BreathShortness,VisualChanges,NoseBleeding,Whendiagnoused,Systolic,Diastolic,ControlledDiet,Stages
0,Male,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
1,Female,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
2,Male,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
3,Female,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
4,Male,51-64,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)

#The 'inplace' attribute is giving errors 👇🏻

In [6]:
# dataset['TakeMedication'].replace({'Yes ':'Yes'}, inplace=True)
# dataset['NoseBleeding'].replace({'No ':'No'}, inplace=True)
# dataset['Systolic'].replace({'121- 130':'121 - 130'}, inplace=True)
# dataset['Systolic'].replace({'100+':'100 - 110'}, inplace=True)
# dataset['Stages'].replace({'HYPERTENSION (Stage-2)':'HYPERTENSION (Stage-2)'}, inplace=True)
# dataset['Stages'].replace({'HYPERTENSIVE CRISI':'HYPERTENSIVE CRISI'}, inplace=True)

# print((dataset['Diastolic'] == '130+').sum())
# print((dataset['Diastolic'] == '100+').sum())

# dataset['Diastolic'].replace({'130+':'100+'}, inplace=True)

#This is the alternate code instead 👇🏻

In [7]:
dataset['TakeMedication'] = dataset['TakeMedication'].replace({'Yes ': 'Yes'})
dataset['NoseBleeding'] = dataset['NoseBleeding'].replace({'No ': 'No'})
dataset['Systolic'] = dataset['Systolic'].replace({'121- 130': '121 - 130', '100+': '100 - 110'})

dataset['Stages'] = dataset['Stages'].replace({
    'HYPERTENSION (Stage-2).': 'HYPERTENSION (Stage-2)',
    'HYPERTENSIVE CRISI': 'HYPERTENSIVE CRISIS'
})

print((dataset['Diastolic'] == '130+').sum())
print((dataset['Diastolic'] == '100+').sum())

dataset['Diastolic'] = dataset['Diastolic'].replace({'130+': '100+'})

4
237

In [8]:
print(dataset.duplicated().sum())

477

In [9]:
dataset.drop_duplicates(inplace=True)

In [10]:
dataset.to_csv('preprocessedData.csv', index=False)